# Generated by Django 5.2.8 on 2025-11-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait_app', '0002_remove_userprofile_role_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripphoto',
            name='image',
            field=models.ImageField(upload_to='trip_photos/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
