# Generated by Django 5.2.8 on 2025-11-29 20:39

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait_app', '0003_alter_tripphoto_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_date'], 'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.AlterModelOptions(
            name='tripphoto',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'Фотография поездки', 'verbose_name_plural': 'Фотографии поездок'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tripphoto',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐ - Плохо'), (2, '⭐⭐ - Удовлетворительно'), (3, '⭐⭐⭐ - Хорошо'), (4, '⭐⭐⭐⭐ - Отлично'), (5, '⭐⭐⭐⭐⭐ - Прекрасно')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Дата начала'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'trip'], name='sait_app_re_user_id_4b3226_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='sait_app_re_created_4cb7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='sait_app_re_rating_9a4825_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved'], name='sait_app_re_is_appr_de5c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'start_date'], name='sait_app_tr_user_id_1c6f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['country'], name='sait_app_tr_country_b52d49_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['created_at'], name='sait_app_tr_created_1c1241_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_date', 'end_date'], name='sait_app_tr_start_d_5b3542_idx'),
        ),
        migrations.AddIndex(
            model_name='tripphoto',
            index=models.Index(fields=['trip', 'order'], name='sait_app_tr_trip_id_c8468f_idx'),
        ),
        migrations.AddIndex(
            model_name='tripphoto',
            index=models.Index(fields=['uploaded_at'], name='sait_app_tr_uploade_ce971e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='sait_app_us_user_id_150b41_idx'),
        ),
    ]
