# Generated by Django 5.2.8 on 2025-11-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait_app', '0004_alter_review_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
    ]
